# Generated by Django 5.2.6 on 2025-09-16 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fish',
            new_name='Product',
        ),
    ]
